### ISSUE TITLE
Potential Deadlock

### ISSUE THREAD

**Issue by anirudhsanthiar** [DineroRegnskab/dinero-csharp-sdk#1]
Dinero wraps asynchronous methods in synchronous wrappers via the `ExecuteSync` method in TaskHelper.cs:
```
public static void ExecuteSync(Func<Task> task)
{
  task().Wait();
}
```
This method blocks on the result of an asynchronous call by calling `Wait` on the result.
Blocking on Task objects (Via Task.Wait() or Task.Result or Task.GetAwaiter().GetResult()) 
is dangerous and could result in deadlocks.
(See, for example [1] (http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html) or [2] (http://blogs.msdn.com/b/pfxteam/archive/2012/04/13/10293638.aspx)).

It is used in the sdk code at several places, for example:
```
public AccountCollection EntryAccountsGetList()
{
  return TaskHelper.ExecuteSync(EntryAccountsGetListAsync);
}
```

These can cause deadlock. To reproduce, could you try invoking the code that follows from a GUI/MVC context? For example, create a simple Windows Forms app with a button click handler that calls this code:
```
 string ClientId = "[INSERT YOUR CLIENT ID HERE]";
 string ClientSecret = "[INSERT YOUR CLIENT SECRET HERE]";
 string ApiKey = "[INSERT THE USERS API KEY HERE]";
 int OrganizationId = 999999999; 
 string EmailForTest = "ApiTest@dinero.dk"; 
 const string PathToSavePdfsTo = null; // <- Replace with path
        
 var client = new ClientCredentials(ClientId, ClientSecret);
 var apiKey = new ApiKey(ApiKey);
 var dinero = new Dinero(client, apiKey, OrganizationId);
 dinero.Accounts.EntryAccountsGetList();
```
Note that to reproduce the deadlock, the code *must* be invoked from a GUI/MVC context - and not a console app/unit test.
I could not test the code because I do not possess the appropriate credentials to authenticate myself to the server, but I shall be happy to supply any other information that is required.

**Comment by larsnikolajsendinero** [comment]
Thanks for the feedback! I was able to reproduce the issue and will push a fix anytime soon :-)

**Comment by larsnikolajsendinero** [comment]
I have pushed a fix for this issue.
