### ISSUE TITLE
How to attach files to ledger items?

### ISSUE THREAD

**Issue by sirpadk** [DineroRegnskab/dinero-csharp-sdk#12]
The SDK allow me to upload a file, and to create a ledger item. But there is no obvious way to connect the ledger item to a file. That basically means that I cannot connect the image of the receipt with the actual ledger item. not really helpful.

I know from the documentation of the app that this is something that is doable in the iPhone app. So is it missing from the SDK only, and can be done using the web service?

Are there any plans to add this to the SDK?
Are there any documentation of the web service?

**Comment by Leh2** [comment]
To attach a file, you should use the property "FileGuid" when creating a ledger item. The property was however missing from the SDK, so I have added it in https://github.com/DineroRegnskab/dinero-csharp-sdk/pull/13.

You can find the api documentation on https://api.dinero.dk/docs.
