### ISSUE TITLE
Client ID in unsecure environment?

### ISSUE THREAD

**Issue by larsbaunwall** [DineroRegnskab/dinero-csharp-sdk#3]
Hi!

Great to see a C# wrapper of your API. Just one question: Any plans for introducing an authentication mechanism, that doesn't rely on a client-id + client-secret?

Currently, this basically prevents me from running any kind of client code on the user's computer, that interacts with the Dinero API (as the client-Id+secret, which is required for every request, in that case is quite easily disassembled).

The same goes for javascript-based client libraries...

Best regards,
Lars

**Comment by larsnikolajsendinero** [comment]
Hi Lars

We are utilizing the authorization server from Thinktecture: https://github.com/IdentityModel/AuthorizationServer which implements the OAuth2 authorization code, implicit, resource owner and client credentials flows. If you write to lars@dinero.dk, I can set up your client to utilize for example the authorization code flow, which might the the thing that you are asking for?

Kind regards
Lars

**Comment by larsbaunwall** [comment]
That's just awesome to hear! :+1: from me!
I'll send you an email shortly :)
