### ISSUE TITLE
Support for account balances and individual ledger transactions?

### ISSUE THREAD

**Issue by larsbaunwall** [DineroRegnskab/dinero-csharp-sdk#4]
Hi

I am working on a budgetting platform, where we would like to fetch ledger transactions from Dinero for our own reporting and budgetting.

I doesn't seem to be possible at the moment in Dinero (as compared to e-conomic and Billys) - any plans for this?

**Comment by larsnikolajsendinero** [comment]
We have no current plans to add this to the API, but I will raise the request
