### ISSUE TITLE
EntryAccountsGetList calls the Async version with the wrong parameter order

### ISSUE THREAD

**Issue by sirpadk** [DineroRegnskab/dinero-csharp-sdk#9]
The method EntryAccountsGetList in the file DineroAccounts.cs has a bug.

The method performs a call to the Async version, using the TaskHelper.ExecuteSync

`return TaskHelper.ExecuteSync(()=> EntryAccountsGetListAsync(fields));`

The result is then an validation exception, as the value in the fields parameter is not a valid category. This happens as the EntryAccountsGetListAsync excepts two parameters, the categoryFilter and the fileds. To fix this bug, the call should be

`return TaskHelper.ExecuteSync(()=> EntryAccountsGetListAsync(categoryFilter, fields));`

**Comment by Leh2** [comment]
Hi @sirpadk,

Thanks for reporting.

Should be fixed in https://github.com/DineroRegnskab/dinero-csharp-sdk/pull/11.
